/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        tertiary: '#904d00',
        'on-tertiary-container': '#723c00',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#002020',
        'secondary-container': '#b7e7fb',
        'on-tertiary': '#ffffff',
        outline: '#6b7a7a',
        'on-primary-container': '#005354',
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-secondary-container': '#39697a',
        'surface-tint': '#00696b',
        'tertiary-fixed': '#ffdcc3',
        'on-error': '#ffffff',
        'on-surface-variant': '#3b4949',
        'tertiary-fixed-dim': '#ffb77d',
        surface: '#f1fbfb',
        'on-primary': '#ffffff',
        'surface-variant': '#dae4e4',
        'surface-container-high': '#e0eaea',
        'tertiary-container': '#ffa557',
        'primary-fixed-dim': '#2ddbde',
        'on-tertiary-fixed': '#2f1500',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#004f51',
        'inverse-surface': '#293232',
        'primary-container': '#00ced1',
        'on-secondary-fixed': '#001f28',
        primary: '#00696b',
        'surface-dim': '#d2dcdc',
        'primary-fixed': '#5af8fb',
        'inverse-primary': '#2ddbde',
        secondary: '#356476',
        'surface-container-highest': '#dae4e4',
        background: '#f1fbfb',
        'on-background': '#141d1e',
        'surface-bright': '#f1fbfb',
        'surface-container': '#e6f0f0',
        'outline-variant': '#bac9c9',
        'on-surface': '#141d1e',
        'secondary-fixed-dim': '#9ecee1',
        'inverse-on-surface': '#e9f3f3',
        'surface-container-low': '#ecf6f6',
        'secondary-fixed': '#baeafe',
        'on-tertiary-fixed-variant': '#6e3900',
        'on-secondary-fixed-variant': '#194d5d',
        'deep-aqua': '#004f51',
        'electric-cyan': '#00ced1',
        'soft-turquoise': '#b7e7fb',
        'vin-orange': '#ffa557',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'unit-lg': '24px',
        'sidebar-width': '280px',
        'unit-sm': '8px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'unit-xs': '4px',
        'unit-xl': '32px',
        gutter: '24px',
        'sidebar-collapsed': '80px',
        'unit-md': '16px',
        'container-max': '1280px',
      },
      fontFamily: {
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-2xl': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-2xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
