package com.asms.core.exception;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    EMAIL_VERIFICATION_REQUIRED,
    EMAIL_ALREADY_REGISTERED,
    VERIFICATION_TOKEN_INVALID,
    VERIFICATION_TOKEN_EXPIRED,
    VERIFICATION_TOKEN_USED,
    AUTH_RATE_LIMITED,
    RATE_LIMIT_SERVICE_UNAVAILABLE,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_REUSED,
    AUTH_SESSION_REVOKED,
    OAUTH_EMAIL_NOT_VERIFIED,
    OAUTH_ONBOARDING_EXPIRED,
    RESET_TOKEN_INVALID,
    RESET_TOKEN_EXPIRED,
    RESET_TOKEN_USED,
    RESET_TOKEN_TYPE_MISMATCH,
    CSRF_VALIDATION_FAILED
}
