package com.asms.core.exception;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    EMAIL_VERIFICATION_REQUIRED,
    EMAIL_ALREADY_REGISTERED,
    VERIFICATION_TOKEN_INVALID,
    VERIFICATION_TOKEN_EXPIRED,
    VERIFICATION_TOKEN_USED,
    AUTH_RATE_LIMITED,
    RATE_LIMIT_SERVICE_UNAVAILABLE
}
